InforShop/src/Entity/Caracteristiques.php
<?php

namespace App\Entity;

use App\Repository\CaracteristiquesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CaracteristiquesRepository::class)
 */
class Caracteristiques
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }



    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numero_modele;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @return mixed
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param mixed $image
     */
    public function setImage($image): void
    {
        $this->image = $image;
    }

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $serie;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $couleur;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $garantie_constructeur;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $systeme_exploitation;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $descrption_clavier;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $marque_processeur;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $type_processeur;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $vitesse_processeur;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $nbr_coeurs;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $taille_memoire_vive;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $taille_disque_dur;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $technologie_disque_dur;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $typeEcran;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tailleEcran;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resEcran;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resMaxEcran;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $descrip_carte_graphique;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $GPU;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $GPU_ram;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type_ram_carte_graphique;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $connectivite;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $bluetooth;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $nbr_ports_HDMI;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $nbr_ports_VGA;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $nbr_ports_USB2;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $nbr_ports_USB3;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $nbr_ports_ethernet;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $typeConnecteur;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $dimensions;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poids;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tailleCable;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $divers;

    /**
     * @ORM\OneToOne(targetEntity=Produits::class, mappedBy="produitscaracteristiques", cascade={"persist", "remove"})
     *
     */
    private $caracteristiquesproduits;




    public function getNumeroModele(): ?string
    {
        return $this->numero_modele;
    }

    public function setNumeroModele(string $numero_modele): self
    {
        $this->numero_modele = $numero_modele;

        return $this;
    }

    public function getSerie(): ?string
    {
        return $this->serie;
    }

    public function setSerie(?string $serie): self
    {
        $this->serie = $serie;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(?string $couleur): self
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getGarantieConstructeur(): ?string
    {
        return $this->garantie_constructeur;
    }

    public function setGarantieConstructeur(?string $garantie_constructeur): self
    {
        $this->garantie_constructeur = $garantie_constructeur;

        return $this;
    }

    public function getSystemeExploitation(): ?string
    {
        return $this->systeme_exploitation;
    }

    public function setSystemeExploitation(?string $systeme_exploitation): self
    {
        $this->systeme_exploitation = $systeme_exploitation;

        return $this;
    }

    public function getDescrptionClavier(): ?string
    {
        return $this->descrption_clavier;
    }

    public function setDescrptionClavier(?string $descrption_clavier): self
    {
        $this->descrption_clavier = $descrption_clavier;

        return $this;
    }

    public function getMarqueProcesseur(): ?string
    {
        return $this->marque_processeur;
    }

    public function setMarqueProcesseur(string $marque_processeur): self
    {
        $this->marque_processeur = $marque_processeur;

        return $this;
    }

    public function getTypeProcesseur(): ?string
    {
        return $this->type_processeur;
    }

    public function setTypeProcesseur(string $type_processeur): self
    {
        $this->type_processeur = $type_processeur;

        return $this;
    }

    public function getVitesseProcesseur(): ?string
    {
        return $this->vitesse_processeur;
    }

    public function setVitesseProcesseur(string $vitesse_processeur): self
    {
        $this->vitesse_processeur = $vitesse_processeur;

        return $this;
    }

    public function getNbrCoeurs(): ?int
    {
        return $this->nbr_coeurs;
    }

    public function setNbrCoeurs(?int $nbr_coeurs): self
    {
        $this->nbr_coeurs = $nbr_coeurs;

        return $this;
    }

    public function getTailleMemoireVive(): ?string
    {
        return $this->taille_memoire_vive;
    }

    public function setTailleMemoireVive(string $taille_memoire_vive): self
    {
        $this->taille_memoire_vive = $taille_memoire_vive;

        return $this;
    }

    public function getTailleDisqueDur(): ?string
    {
        return $this->taille_disque_dur;
    }

    public function setTailleDisqueDur(?string $taille_disque_dur): self
    {
        $this->taille_disque_dur = $taille_disque_dur;

        return $this;
    }

    public function getTechnologieDisqueDur(): ?string
    {
        return $this->technologie_disque_dur;
    }

    public function setTechnologieDisqueDur(?string $technologie_disque_dur): self
    {
        $this->technologie_disque_dur = $technologie_disque_dur;

        return $this;
    }

    public function getTypeEcran(): ?string
    {
        return $this->typeEcran;
    }

    public function setTypeEcran(?string $typeEcran): self
    {
        $this->typeEcran = $typeEcran;

        return $this;
    }

    public function getTailleEcran(): ?string
    {
        return $this->tailleEcran;
    }

    public function setTailleEcran(?string $tailleEcran): self
    {
        $this->tailleEcran = $tailleEcran;

        return $this;
    }

    public function getResEcran(): ?string
    {
        return $this->resEcran;
    }

    public function setResEcran(?string $resEcran): self
    {
        $this->resEcran = $resEcran;

        return $this;
    }

    public function getResMaxEcran(): ?string
    {
        return $this->resMaxEcran;
    }

    public function setResMaxEcran(?string $resMaxEcran): self
    {
        $this->resMaxEcran = $resMaxEcran;

        return $this;
    }

    public function getDescripCarteGraphique(): ?string
    {
        return $this->descrip_carte_graphique;
    }

    public function setDescripCarteGraphique(?string $descrip_carte_graphique): self
    {
        $this->descrip_carte_graphique = $descrip_carte_graphique;

        return $this;
    }

    public function getGPU(): ?string
    {
        return $this->GPU;
    }

    public function setGPU(?string $GPU): self
    {
        $this->GPU = $GPU;

        return $this;
    }

    public function getGPURam(): ?string
    {
        return $this->GPU_ram;
    }

    public function setGPURam(?string $GPU_ram): self
    {
        $this->GPU_ram = $GPU_ram;

        return $this;
    }

    public function getTypeRamCarteGraphique(): ?string
    {
        return $this->type_ram_carte_graphique;
    }

    public function setTypeRamCarteGraphique(?string $type_ram_carte_graphique): self
    {
        $this->type_ram_carte_graphique = $type_ram_carte_graphique;

        return $this;
    }

    public function getConnectivite(): ?string
    {
        return $this->connectivite;
    }

    public function setConnectivite(?string $connectivite): self
    {
        $this->connectivite = $connectivite;

        return $this;
    }

    public function getBluetooth(): ?string
    {

InforShop/src/Controller/PropertyController.php
<?php
namespace App\Controller;

use App\Entity\Produits;
use App\Entity\ProduitsSearch;
use App\Form\ProduitsSearchType;
use App\Repository\ProduitsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController

{
    /**
     * @var ProduitsRepository
     */
    private $repository;

    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(ProduitsRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/Produits",name="property.index" )
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new ProduitsSearch();
        $form = $this->createForm(ProduitsSearchType::class, $search);
        $form->handleRequest($request);

        $produitz = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1 ),12
        );

        return $this->render('property/index.html.twig', [
            'current_menu' => 'produitz',
            'produitz' => $produitz,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/Produits/detail{id}",name="property.detail" )
     * @return Response
     */
    public function indexdetail(Produits $produitz): Response
    {
        return $this->render('property/detail.html.twig', [
            'produitz' => $produitz
        ]);
    }

}

InforShop/templates/property/detail.html.twig
{% extends 'base.html.twig' %}

{%  block title 'InforShop' %}

{% block body %}

    <div class="jumbotron">
        <h1 class="display-4">{{ produitz.marque }} - {{ produitz.produitscaracteristiques.serie }}</h1>
        <div class="card-image">
            <img src="/images/products/{{ produitz.filename }}" alt="card-img-top" style="width: auto; height: 200px">
        </div>
        <p class="lead"> {{ produitz.categorie }}</p>
        {% if produitz.categorie == 'écran' %}
            <p>
                {{ produitz.produitscaracteristiques.tailleEcran}} {{ produitz.produitscaracteristiques.typeEcran }} {{ produitz.produitscaracteristiques.resEcran }} ,
                {{ produitz.produitscaracteristiques.typeConnecteur}} {{ produitz.produitscaracteristiques.tailleCable}} ,
                {{ produitz.produitscaracteristiques.dimensions}} {{ produitz.produitscaracteristiques.poids}} {{ produitz.produitscaracteristiques.divers}}
            </p>
        {% else %}
            <p>
                {{ produitz.produitscaracteristiques.marqueProcesseur }} {{ produitz.produitscaracteristiques.typeProcesseur }} {{ produitz.produitscaracteristiques.vitesseProcesseur }}
                , {{ produitz.produitscaracteristiques.gPU }} {{ produitz.produitscaracteristiques.gPURam }}
                , {{ produitz.produitscaracteristiques.technologieDisqueDur }} {{ produitz.produitscaracteristiques.tailleDisqueDur }}
                , {{ produitz.produitscaracteristiques.tailleMemoireVive }} {{ produitz.produitscaracteristiques.typeRamCarteGraphique }}
                , {{ produitz.produitscaracteristiques.systemeExploitation }}

            </p>
        {% endif %}
        <hr class="my-4">
        <p> Description Description Description Description Description Description Description Description
            Description Description Description Description Description Description Description Description
            Description Description Description Description Description Description Description Description</p>
        {% if produitz.produitspromotions == NULL %}<h2>{{ produitz.prix }} €</h2>
        {% else %} <h2> <s>{{ produitz.prix }}€</s> {{ produitz.prix-((produitz.prix/100)*(produitz.produitspromotions.remise)) }}$(-{{ produitz.produitspromotions.remise }}%) </h2>
        {% endif %}
        {% if produitz.quantite == 0 %}<p> Stock épuisé </p>
        {% else %}
            <p class="lead">
                <a href="{{ path('Panier.add', {id: produitz.id }) }}" class="btn btn-success btn-lg" role="button">
                    <i class="fas fa-shopping-cart mr-1">Ajouter au panier</i>
                </a>
            </p>
        {% endif %}

    </div>

{% endblock %}

InforShop/templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tous nos produits' %}
{% block body%}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row">
                <div class="col">
                    {{ form_row(form.maxPrix) }}
                </div>
                <div class="col">
                    {{ form_row(form.minPrix) }}
                </div>
                <div class="col">
                    <button class="btn btn-primary">Recherche</button>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
    <div class="container mt-4">
        <h1>Tous nos produits</h1>

    </div>
    <div class="container">
        <div class="row flex">
            {% for produits in produitz %}
            <div class="col-5">
                <div class="card">
                    <div class="card-image">
                        <img src="/images/products/{{ produits.filename }}" alt="card-img-top" style="width: auto; height: 200px">
                    </div>
                    <div class="card-body">
                        <h3 class="card-title">
                            <a href="{{ path('property.detail',{id: produits.id})}}">{{ produits.marque }} - {{ produits.nom }}</a>
                        </h3>
                        <div class="text-muted">{{ produits.produitscaracteristiques.marqueProcesseur }} {{ produits.produitscaracteristiques.typeProcesseur }} {{ produits.produitscaracteristiques.nbrCoeurs }},
                            {{ produits.produitscaracteristiques.technologieDisqueDur }} {{ produits.produitscaracteristiques.tailleDisqueDur}} ,{{ produits.produitscaracteristiques.tailleMemoireVive }}</div>
                        {% if produits.produitspromotions == NULL %}<h2>{{ produits.prix }} €</h2>
                        {% else %}<p> <s>{{ produits.prix }}€</s> {{ produits.prix-((produits.prix/100)*(produits.produitspromotions.remise)) }}€(-{{ produits.produitspromotions.remise }}%) </p>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="pagination">
            {{ knp_pagination_render(produitz) }}
        </div>
    </div>
{% endblock %}